/*
 *
 * Product constants
 *
 */

// Product Type
export const FETCH_PRODUCT_TYPE = 'FETCH_PRODUCT_TYPE';
export const FETCH_PRODUCT_TYPE_SUCCESS = 'FETCH_PRODUCT_TYPE_SUCCESS';
export const FETCH_PRODUCT_TYPE_FAILED = 'FETCH_PRODUCT_TYPE_FAILED';
export const SET_PRODUCT_TYPE_LIST = 'SET_PRODUCT_TYPE_LIST';

// Product
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';

// Manufacturer
export const FETCH_MANUFACTURER = 'FETCH_MANUFACTURER';
export const FETCH_MANUFACTURER_SUCCESS = 'FETCH_MANUFACTURER_SUCCESS';
export const FETCH_MANUFACTURER_FAILED = 'FETCH_MANUFACTURER_FAILED';
export const SET_MANUFACTURER_LIST = 'SET_MANUFACTURER_LIST';

// Distributor
export const FETCH_DISTRIBUTOR = 'FETCH_DISTRIBUTOR';
export const FETCH_DISTRIBUTOR_SUCCESS = 'FETCH_DISTRIBUTOR_SUCCESS';
export const FETCH_DISTRIBUTOR_FAILED = 'FETCH_DISTRIBUTOR_FAILED';
export const SET_DISTRIBUTOR_LIST = 'SET_DISTRIBUTOR_LIST';
